// Precompiles the ajv validators this package ships: the default validator for the full
// opportunity schema, plus one per fundingDetails branch (mirrors errors.ts's DEF_BY_TAG,
// used there to re-validate a failed `fundingDetails` against the one shape its tag names).
//
// Why this exists: ajv normally compiles a schema into a validator by generating source and
// calling `new Function` on it (`ajv.compile`, used at runtime by validator.ts/errors.ts today).
// That throws under a strict CSP with no `unsafe-eval` — exactly what the RFP Hub dashboard now
// ships, which silently killed in-browser conformance checking. ajv's standalone code generation
// produces the same validator as plain, already-generated JS functions instead, so this package
// never has to call `new Function` at runtime for the standard's own schema.
//
// ajv's standalone output isn't self-contained on its own: it references its own runtime helpers
// (equal, ucs2length) and ajv-formats' format functions via `require(...)`, meant to be resolved
// by a bundler rather than executed directly (see ajv's standalone docs). Leaving that to tsup
// would fail, since tsup externalizes `ajv`/`ajv-formats` — they're real `dependencies` of this
// package, needed at runtime by createValidator()'s custom-schema path and by the CLI. So this
// script bundles the generated code with esbuild itself, inlining those requires, which is what
// makes the *committed* artifact fully self-contained: zero live `require()`, zero `new Function`.
//
// Output (committed; `--check` verifies it is in sync and never writes):
//   - src/generated/validators.js    the precompiled validators (ESM, self-contained)
//   - src/generated/validators.d.ts  type declarations for the above
//
// Regenerate with `pnpm codegen` whenever @the-rfp-hub/standard's schema changes.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { opportunitySchema } from "@the-rfp-hub/standard";
import addFormats from "ajv-formats";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import * as esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const p = (...parts) => resolve(pkgRoot, ...parts);
const readText = (f) => readFileSync(f, "utf8");

/** Same ajv configuration and annotation keywords as validator.ts's createValidator(). */
const ANNOTATION_KEYWORDS = ["x-stability", "x-since", "x-deprecated"];

const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  strictRequired: false,
  code: { source: true, esm: true },
});
addFormats(ajv);
for (const keyword of ANNOTATION_KEYWORDS) ajv.addKeyword(keyword);

ajv.addSchema(opportunitySchema, "opportunity");

/** fundingType tag -> $defs name, read from each def's `const` tag — same derivation errors.ts's DEF_BY_TAG uses. */
const defByTag = new Map(
  Object.entries(opportunitySchema.$defs ?? {}).flatMap(([name, def]) => {
    const tag = def.properties?.fundingType?.const;
    return typeof tag === "string" ? [[tag, name]] : [];
  }),
);
if (defByTag.size === 0) {
  throw new Error(
    "codegen: no fundingType-tagged $defs found in opportunitySchema — schema shape changed?",
  );
}

/** tag -> the standalone export name compiled for that branch's schema. */
const branchExportNames = new Map();
for (const [tag, defName] of defByTag) {
  const exportName = `branch_${defName}`;
  branchExportNames.set(tag, exportName);
  ajv.addSchema(
    {
      $schema: opportunitySchema.$schema,
      $defs: opportunitySchema.$defs,
      $ref: `#/$defs/${defName}`,
    },
    exportName,
  );
}

let code = standaloneCode(ajv);
const branchesEntries = [...branchExportNames.entries()]
  .map(([tag, exportName]) => `  ${JSON.stringify(tag)}: ${exportName},`)
  .join("\n");
code += `\nexport const branches = {\n${branchesEntries}\n};\n`;

const bundled = await esbuild.build({
  stdin: { contents: code, resolveDir: pkgRoot, loader: "js" },
  bundle: true,
  write: false,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  legalComments: "none",
});
if (bundled.outputFiles.length !== 1) {
  throw new Error(
    `codegen: expected exactly one esbuild output file, got ${bundled.outputFiles.length}`,
  );
}

const banner = [
  "// GENERATED by scripts/codegen.mjs from @the-rfp-hub/standard's opportunity.schema.json.",
  "// Do not edit by hand. Regenerate with `pnpm codegen`.",
  "//",
  "// Precompiled with ajv's standalone code generation, bundled with esbuild so ajv's own",
  "// runtime helpers and ajv-formats' format functions are inlined rather than `require`d.",
  "// This is what lets rfphub-validate validate the standard's schema without ever calling",
  "// `new Function` at runtime — required for consumers under a strict CSP (script-src with",
  "// no unsafe-eval), such as the RFP Hub dashboard's in-browser conformance checker.",
  "/* biome-ignore-all lint: generated */",
].join("\n");

const jsText = `${banner}\n${bundled.outputFiles[0].text}`;

const dtsText = [
  banner,
  'import type { ValidateFunction } from "ajv";',
  "",
  "/** Precompiled validator for the full opportunity schema. */",
  "export declare const opportunity: ValidateFunction;",
  "",
  "/** Precompiled per-branch fundingDetails validators, keyed by the standard's `fundingType` tag values. */",
  "export declare const branches: Record<string, ValidateFunction>;",
  "",
].join("\n");

const outputs = [
  [p("src", "generated", "validators.js"), jsText],
  [p("src", "generated", "validators.d.ts"), dtsText],
];

if (process.argv.includes("--check")) {
  const stale = outputs.filter(([file, want]) => (existsSync(file) ? readText(file) : "") !== want);
  if (stale.length > 0) {
    const list = stale.map(([f]) => `  - ${f.slice(pkgRoot.length + 1)}`).join("\n");
    console.error(
      `✗ ${stale.length} generated artifact(s) out of sync with @the-rfp-hub/standard's schema:\n${list}\n  Run \`pnpm codegen\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`✓ ${outputs.length} generated artifacts are in sync`);
} else {
  for (const [file, content] of outputs) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${file.slice(pkgRoot.length + 1)}`);
  }
}
