/**
 * Better-Auth's own tables — `auth_user`, `auth_session`, `auth_account`, `auth_verification`.
 *
 * WHERE THIS CAME FROM. `npx @better-auth/cli generate` was run once against a config mirroring
 * the real composition (`emailOTP`, `bearer({requireSignature:true})`, `oneTimeToken`,
 * `drizzleAdapter(db,{provider:"pg"})`, the `auth_*` `modelName`s below) and then HAND-CORRECTED
 * against the schema the installed `better-auth@1.7.1` runtime actually builds
 * (`@better-auth/core/db/get-tables.mjs`, via `buildAuthTables`) — the CLI package
 * (`@better-auth/cli`, latest published release `1.4.21`) trails the pinned `1.7.1` core and its
 * generated draft was WRONG in two ways this file does not repeat:
 *
 *   1. It omitted `auth_account.issuer` entirely. 1.7.1 scopes account identity by
 *      `(issuer, accountId)`, not `(providerId, accountId)` — see the runtime's own upgrade note,
 *      "account identity is scoped by issuer". `issuer` is a synthetic string the library derives
 *      per provider (`local:<providerId>` for credential-style providers, `local:oauth:<providerId>`
 *      for OAuth ones) — never supplied by a caller, so it needs no default here.
 *   2. It emitted no unique constraint on `auth_account` at all. `buildAuthTables` declares
 *      `{ fields: ["issuer", "accountId"], unique: true }` as a table-level index — this is the
 *      constraint `linkAccount`/`findAccountOwnerByKey` rely on, and the one the plan's Risk 3
 *      tripwire (`integration/account-linking.test.ts`, a later phase) exists to keep honest.
 *
 * None of the three plugins wired in (`emailOTP`, `bearer`, `oneTimeToken`) add a table or a field
 * of their own — verified by reading their plugin definitions; only `emailOTP`'s OpenAPI response
 * schemas contain the word "schema", not a DB one. So these four tables are the complete surface.
 *
 * WHY THIS FILE IS NOT REGENERATED BY `db:generate`. `drizzle-kit generate` diffs THIS file's
 * `pgTable` calls against the migrations directory, same as every other table in `schema.ts` — it
 * does not know or care that these definitions originated from Better-Auth. There is no ongoing
 * codegen step; a future Better-Auth bump is reviewed by hand against `get-tables.mjs` again, the
 * same way this first cut was.
 *
 * WHY `public` SCHEMA, WHY THESE `modelName`s, WHY `auth_user_id` HAS NO FK: see
 * `plan §0 #3, #3a` / `docs/data-model.md`. In short: the E2E runtime role is granted
 * `ON ALL TABLES IN SCHEMA public` only, so a `schemaName:"auth"` table would be invisible to it;
 * and `accounts.auth_user_id` (in `schema.ts`) deliberately carries no FK to `auth_user.id` because
 * an `accounts` row must outlive an `auth_user` row — `audit_log` points at the former, never the
 * latter.
 *
 * WHY THESE FOUR TABLES CASCADE ON `auth_user_id`/`user_id` WHILE `accounts` DOES NOT: these tables
 * belong to Better-Auth, not to this application's data model. A session or a linked provider
 * account has no meaning once its `auth_user` is gone, so cascading here is simply keeping
 * Better-Auth's own referential integrity — it is not the same design question as the app's
 * `accounts` table, which is deliberately outlived by its own foreign referrers.
 */
import { boolean, index, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

// ── auth_user ──────────────────────────────────────────────────────────────────
export const authUser = pgTable("auth_user", {
  /** Better-Auth's default id generation (a CSPRNG string minted in JS) — see plan §0 #3b. */
  id: text().primaryKey(),
  name: text().notNull(),
  /** Lower-cased by Better-Auth before it ever reaches the adapter; not re-enforced here. */
  email: text().notNull().unique(),
  emailVerified: boolean().notNull().default(false),
  image: text(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});

// ── auth_session ───────────────────────────────────────────────────────────────
export const authSession = pgTable(
  "auth_session",
  {
    id: text().primaryKey(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    /**
     * The opaque bearer credential. UNIQUE is what `SessionService.verify` (plan §2 P2) leans on —
     * signing out deletes the row, so the very next lookup by token is a clean miss, not a stale
     * hit against a duplicate.
     */
    token: text().notNull().unique(),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    ipAddress: text(),
    userAgent: text(),
    userId: text()
      .notNull()
      .references(() => authUser.id, { onDelete: "cascade" }),
  },
  (t) => [index("ix_auth_session_user").on(t.userId)],
);

// ── auth_account ───────────────────────────────────────────────────────────────
export const authAccount = pgTable(
  "auth_account",
  {
    id: text().primaryKey(),
    /**
     * The provider-scoped subject. On its own it is NOT globally unique — see `issuer` below, and
     * the header comment on why `(issuer, accountId)` is the real key.
     */
    accountId: text().notNull(),
    providerId: text().notNull(),
    /**
     * The scope `accountId` is unique WITHIN. Synthetic and library-derived (`local:credential`,
     * `local:oauth:google`, …) — never client-supplied. See the header comment for why 1.7.1 added
     * this column and what the CLI's stale draft got wrong by omitting it.
     */
    issuer: text().notNull(),
    userId: text()
      .notNull()
      .references(() => authUser.id, { onDelete: "cascade" }),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: timestamp({ withTimezone: true }),
    refreshTokenExpiresAt: timestamp({ withTimezone: true }),
    /** Accumulated OAuth grant, comma-separated — the union of every scope ever consented to. */
    scope: text(),
    /** Populated only for the (unused, per plan §0 #2 — OTP only, no password) credential provider. */
    password: text(),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // THE constraint `linkAccount`/`findAccountOwnerByKey` depend on — see the header comment.
    uniqueIndex("ux_auth_account_issuer_account").on(t.issuer, t.accountId),
    index("ix_auth_account_user").on(t.userId),
  ],
);

// ── auth_verification ─────────────────────────────────────────────────────────
/** OTP codes and any other short-lived, single-use verification value Better-Auth mints. */
export const authVerification = pgTable(
  "auth_verification",
  {
    id: text().primaryKey(),
    /** What is being verified — an email address for `emailOTP`. */
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("ix_auth_verification_identifier").on(t.identifier)],
);

export type AuthUserRow = typeof authUser.$inferSelect;
export type AuthSessionRow = typeof authSession.$inferSelect;
export type AuthAccountRow = typeof authAccount.$inferSelect;
export type AuthVerificationRow = typeof authVerification.$inferSelect;
